DROP DATABASE IF EXISTS proxy;
CREATE DATABASE proxy;
USE proxy;

DROP USER IF EXISTS 'anonkorea4869'@'%';
CREATE USER 'anonkorea4869'@'%' IDENTIFIED BY 'anonkorea4869';
GRANT ALL PRIVILEGES ON proxy.* TO 'anonkorea4869'@'%';
FLUSH PRIVILEGES;

DROP TABLE IF EXISTS logs;
CREATE TABLE logs (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    src VARCHAR(255) NOT NULL,
    dest VARCHAR(255) NOT NULL,
    dest_ip VARCHAR(255) NOT NULL,
    dest_port INT DEFAULT NULL,
    method VARCHAR(255) NOT NULL,
    list_type ENUM('deny', 'allow') NOT NULL,
    score FLOAT CHECK (score >= 0 AND score <= 1) NOT NULL,
    reason JSON DEFAULT NULL,
    time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS domain;
CREATE TABLE domain (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    list_type ENUM('deny', 'allow') NOT NULL,
    domain VARCHAR(255) NOT NULL,
    description TEXT DEFAULT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_domain (domain)
);

DROP TABLE IF EXISTS cidr;
CREATE TABLE cidr (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    list_type ENUM('deny', 'allow') NOT NULL,
    cidr VARCHAR(43) NOT NULL,
    description TEXT DEFAULT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_cidr (cidr)
);

DROP TABLE IF EXISTS hide;
CREATE TABLE hide (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    domain VARCHAR(255) NOT NULL,
    description TEXT DEFAULT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_domain (domain)
);
